version: '3.8'
services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command: ["rasa", "run", "--enable-api", "--cors", "*", "--endpoints", "endpoints.yml"]

  action_server:
    image: rasa/rasa-sdk:latest
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command: ["start"]

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/qWeRtY2*
    ports:
      - "7474:7474"
      - "7687:7687"