version: '3.8'

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    command: ["rasa", "run", "--enable-api", "--cors", "*"]

  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - .:/app/actions
    ports:
      - "5055:5055"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"