version: '3.8'

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    command: ["rasa", "run", "--enable-api", "--cors", "*"]

  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - .:/app/actions
    ports:
      - "5055:5055"

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474"
      - "7687:7687"